version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.6
    steps:
    - checkout
    - run:
        command: |
          sudo pip install pipenv
          pipenv install
        name: Install pipenv
    - run:
        command: |
          pipenv run python edim.py
        name: Execute test
    - run:
        command: |
          pipenv run pyinstaller edim.py --onefile
        name: Build binary
    - run:
        command: |
          pipenv run coverage run edim.py
          pipenv run codecov -t $CODECOV_TOKEN
        name: Create & send report
workflows:
  Test Workflow:
    jobs:
    - test
  version: 2
